name: Pack files and release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm run build

      - name: Pack plugin
        run: pnpm run plugin:pack

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: com.zikai.racetelemetry.flexplugin
